# ========================
# Global Config / Metadata
# ========================

PROCESS_NAME = "castle.exe"

# Memory Layout Constants
STRUCT_SIZE = 48  # Size of one character struct (bytes)
PADDING_LENGTH = 16  # Trailing padding (bytes)
PRECEDING_ZEROES = 32  # Required zero bytes before first valid character struct

# Scan Behavior
FAST_SCAN = True  # True = fast scan, False = full memory scan
FAST_SCAN_START_ADDRESS = 0x07000000  # Only used if FAST_SCAN=True

# ========================
# Game Content Data
# ========================

CHARACTERS = {
    "Green Knight": {"id": 1, "image": "images/castle_crashers/characters/321.png"},
    "Red Knight": {"id": 2, "image": "images/castle_crashers/characters/322.png"},
    "Blue Knight": {"id": 3, "image": "images/castle_crashers/characters/323.png"},
    "Orange Knight": {"id": 4, "image": "images/castle_crashers/characters/324.png"},
    "Gray Knight": {"id": 5, "image": "images/castle_crashers/characters/325.png"},
    "Barbarian": {"id": 6, "image": "images/castle_crashers/characters/326.png"},
    "Thief": {"id": 7, "image": "images/castle_crashers/characters/327.png"},
    "Fencer": {"id": 8, "image": "images/castle_crashers/characters/328.png"},
    "Beekeeper": {"id": 9, "image": "images/castle_crashers/characters/329.png"},
    "Industrialist": {"id": 10, "image": "images/castle_crashers/characters/330.png"},
    "Alien": {"id": 11, "image": "images/castle_crashers/characters/331.png"},
    "King": {"id": 12, "image": "images/castle_crashers/characters/332.png"},
    "Brute": {"id": 13, "image": "images/castle_crashers/characters/333.png"},
    "Snakey": {"id": 14, "image": "images/castle_crashers/characters/334.png"},
    "Saracen": {"id": 15, "image": "images/castle_crashers/characters/335.png"},
    "Royal Guard": {"id": 16, "image": "images/castle_crashers/characters/336.png"},
    "Stoveface": {"id": 17, "image": "images/castle_crashers/characters/337.png"},
    "Peasant": {"id": 18, "image": "images/castle_crashers/characters/338.png"},
    "Bear": {"id": 19, "image": "images/castle_crashers/characters/339.png"},
    "Necromancer": {"id": 20, "image": "images/castle_crashers/characters/340.png"},
    "Conehead": {"id": 21, "image": "images/castle_crashers/characters/341.png"},
    "Civilian": {"id": 22, "image": "images/castle_crashers/characters/342.png"},
    "Open-Faced Gray Knight": {
        "id": 23,
        "image": "images/castle_crashers/characters/343.png",
    },
    "Fire Demon": {"id": 24, "image": "images/castle_crashers/characters/344.png"},
    "Skeleton": {"id": 25, "image": "images/castle_crashers/characters/345.png"},
    "Iceskimo": {"id": 26, "image": "images/castle_crashers/characters/346.png"},
    "Ninja": {"id": 27, "image": "images/castle_crashers/characters/347.png"},
    "Cult Minion": {"id": 28, "image": "images/castle_crashers/characters/348.png"},
    "Pink Knight": {"id": 29, "image": "images/castle_crashers/characters/349.png"},
    "Blacksmith": {"id": 30, "image": "images/castle_crashers/characters/350.png"},
    "Hatty Hattington": {
        "id": 31,
        "image": "images/castle_crashers/characters/351.png",
    },
    "Paint Junior": {"id": 32, "image": "images/castle_crashers/characters/352.png"},
    "Custom Character Slot 1": {
        "id": 33,
        "image": "images/castle_crashers/characters/163.png",
    },
    "Custom Character Slot 2": {
        "id": 34,
        "image": "images/castle_crashers/characters/163.png",
    },
    "Custom Character Slot 3": {
        "id": 35,
        "image": "images/castle_crashers/characters/163.png",
    },
    "Custom Character Slot 4": {
        "id": 36,
        "image": "images/castle_crashers/characters/163.png",
    },
    "Custom Character Slot 5": {
        "id": 37,
        "image": "images/castle_crashers/characters/163.png",
    },
    "Custom Character Slot 6": {
        "id": 38,
        "image": "images/castle_crashers/characters/163.png",
    },
    "Custom Character Slot 7": {
        "id": 39,
        "image": "images/castle_crashers/characters/163.png",
    },
    "Custom Character Slot 8": {
        "id": 40,
        "image": "images/castle_crashers/characters/163.png",
    },
    "Custom Character Slot 9": {
        "id": 41,
        "image": "images/castle_crashers/characters/163.png",
    },
    "Custom Character Slot 10": {
        "id": 42,
        "image": "images/castle_crashers/characters/163.png",
    },
}

WEAPONS = [
    ("Unpickupable Statless Skinny Sword", 0),
    ("Statless Skinny Sword", 1),
    ("Skinny Sword", 2),
    ("Thin Sword", 3),
    ("Thick Sword", 4),
    ("Pumpkin Peeler", 5),
    ("Gladiator Sword", 6),
    ("Butcher Knife", 7),
    ("Half Sword", 8),
    ("Carrot", 9),
    ("Thief Sword", 10),
    ("Gold Sword", 11),
    ("Dual Prong Sword", 12),
    ("Zigzag", 13),
    ("Playdo Pasta Maker", 14),
    ("Falchion", 15),
    ("Pointy Sword", 16),
    ("Chewed Up Sword", 17),
    ("Fencer's Foil", 18),
    ("Barbarian Ax", 19),
    ("Pitchfork", 20),
    ("Curved Sword", 21),
    ("Key Sword", 22),
    ("Apple Peeler", 23),
    ("Rubber-Handle Sword", 24),
    ("Mace", 25),
    ("Club", 26),
    ("Ugly Mace", 27),
    ("Refined Mace", 28),
    ("Fish", 29),
    ("Wrapped Sword", 30),
    ("Skeletor Mace", 31),
    ("Clunky Mace", 32),
    ("Snakey Mace", 33),
    ("Rat Beating Bat", 34),
    ("Black Morning Star", 35),
    ("King's Mace", 36),
    ("Meat Tenderizer", 37),
    ("Leaf", 38),
    ("Sheathed Sword", 39),
    ("Practice Foil", 40),
    ("Twig", 41),
    ("Leafy Twig", 42),
    ("Light Saber", 43),
    ("Staff", 44),
    ("Wooden Spoon", 45),
    ("Bone Leg", 46),
    ("Alien Gun", 47),
    ("Fishing Spear", 48),
    ("Lance", 49),
    ("Sai", 50),
    ("Unicorn Horn", 51),
    ("Ribeye", 52),
    ("Kielbasa", 53),
    ("Lobster", 54),
    ("Umbrella", 55),
    ("Broad Ax", 56),
    ("Evil Sword", 57),
    ("Ice Sword", 58),
    ("Candlestick", 59),
    ("Panic Mallet", 60),
    ("Fishing Rod", 61),
    ("Wrench", 62),
    ("NG Lollipop", 63),
    ("Gold Skull Mace", 64),
    ("NG Golden Sword", 65),
    ("Chainsaw", 66),
    ("Broad Spear", 67),
    ("Glowstick", 68),
    ("Chicken Stick", 69),
    ("Demon Sword", 70),
    ("Broccoli Sword", 71),
    ("Man Catcher", 72),
    ("Wooden Mace", 73),
    ("Ninja Claw", 74),
    ("Buffalo Mace", 75),
    ("Electric Eel", 76),
    ("Scissors", 77),
    ("Dinner Fork", 78),
    ("Cattle Prod", 79),
    ("Lightning Bolt", 80),
    ("2x4", 81),
    ("Wooden Sword", 82),
    ("Cardboard Tube", 83),
    ("Emerald Sword", 84),
    ("Hammer", 85),
    ("Pencil", 86),
    ("Invisible Sword", 87),
    ("Invisible Sword", 88),
    ("Invisible Sword", 89),
    ("Invisible Sword", 90),
    ("Invisible Sword", 91),
    ("Invisible Sword", 92),
    ("Invisible Map", 93),
    ("Invisible Horn", 94),
    ("Arrow", 95),
    ("Invisible Shovel", 96),
    ("Map", 97),
    ("Horn", 98),
    ("Arrow", 99),
    ("Shovel", 100),
    ("Invisible Sword", 101),
    ("Invisible Sword", 102),
    ("Invisible Sword", 103),
    ("Invisible Sword", 104),
    ("Invisible Sword", 105),
    ("Invisible Sword", 106),
    ("Invisible Sword", 107),
    ("Invisible Sword", 108),
    ("Invisible Sword", 109),
    ("Invisible Sword", 110),
    ("Invisible Sword", 111),
    ("Invisible Sword", 112),
    ("Invisible Sword", 113),
    ("Invisible Sword", 114),
    ("Invisible Sword", 115),
    ("Invisible Sword", 116),
    ("Invisible Sword", 117),
    ("Invisible Sword", 118),
    ("Invisible Sword", 119),
    ("Invisible Sword", 120),
    ("Invisible Sword", 121),
    ("Invisible Sword", 122),
    ("Invisible Sword", 123),
    ("Invisible Sword", 124),
    ("Invisible Sword", 125),
    ("Invisible Sword", 126),
    ("Invisible Sword", 127),
    ("Purple Unpickupable Statless Skinny Sword", 128),
    ("Purple Statless Skinny Sword", 129),
    ("Purple Skinny Sword", 130),
    ("Purple Thin Sword", 131),
    ("Purple Thick Sword", 132),
    ("Purple Pumpkin Peeler", 133),
    ("Purple Gladiator Sword", 134),
    ("Purple Butcher Knife", 135),
    ("Purple Half Sword", 136),
    ("Purple Carrot", 137),
    ("Purple Thief Sword", 138),
    ("Purple Gold Sword", 139),
    ("Purple Dual Prong Sword", 140),
    ("Purple Zigzag", 141),
    ("Purple Playdo Pasta Maker", 142),
    ("Purple Falchion", 143),
    ("Purple Pointy Sword", 144),
    ("Purple Chewed Up Sword", 145),
    ("Purple Fencer's Foil", 146),
    ("Purple Barbarian Ax", 147),
    ("Purple Pitchfork", 148),
    ("Purple Curved Sword", 149),
    ("Purple Key Sword", 150),
    ("Purple Apple Peeler", 151),
    ("Purple Rubber-Handle Sword", 152),
    ("Purple Mace", 153),
    ("Purple Club", 154),
    ("Purple Ugly Mace", 155),
    ("Purple Refined Mace", 156),
    ("Purple Fish", 157),
    ("Purple Wrapped Sword", 158),
    ("Purple Skeletor Mace", 159),
    ("Purple Clunky Mace", 160),
    ("Purple Snakey Mace", 161),
    ("Purple Rat Beating Bat", 162),
    ("Purple Black Morning Star", 163),
    ("Purple King's Mace", 164),
    ("Purple Meat Tenderizer", 165),
    ("Purple Leaf", 166),
    ("Purple Sheathed Sword", 167),
    ("Purple Practice Foil", 168),
    ("Purple Twig", 169),
    ("Purple Leafy Twig", 170),
    ("Purple Light Saber", 171),
    ("Purple Staff", 172),
    ("Purple Wooden Spoon", 173),
    ("Purple Bone Leg", 174),
    ("Purple Alien Gun", 175),
    ("Purple Fishing Spear", 176),
    ("Purple Lance", 177),
    ("Purple Sai", 178),
    ("Purple Unicorn Horn", 179),
    ("Purple Ribeye", 180),
    ("Purple Kielbasa", 181),
    ("Purple Lobster", 182),
    ("Purple Umbrella", 183),
    ("Purple Broad Ax", 184),
    ("Purple Evil Sword", 185),
    ("Purple Ice Sword", 186),
    ("Purple Candlestick", 187),
    ("Purple Panic Mallet", 188),
    ("Purple Fishing Rod", 189),
    ("Purple Wrench", 190),
    ("Purple NG Lollipop", 191),
    ("Purple Gold Skull Mace", 192),
    ("Purple NG Golden Sword", 193),
    ("Purple Chainsaw", 194),
    ("Purple Broad Spear", 195),
    ("Purple Glowstick", 196),
    ("Purple Chicken Stick", 197),
    ("Purple Demon Sword", 198),
    ("Purple Broccoli Sword", 199),
    ("Purple Man Catcher", 200),
    ("Purple Wooden Mace", 201),
    ("Purple Ninja Claw", 202),
    ("Purple Buffalo Mace", 203),
    ("Purple Electric Eel", 204),
    ("Purple Scissors", 205),
    ("Purple Dinner Fork", 206),
    ("Purple Cattle Prod", 207),
    ("Purple Lightning Bolt", 208),
    ("Purple 2x4", 209),
    ("Purple Wooden Sword", 210),
    ("Purple Cardboard Tube", 211),
    ("Purple Emerald Sword", 212),
    ("Purple Hammer", 213),
    ("Purple Pencil", 214),
    ("Invisible Purple Pencil", 215),
]

ANIMAL_ORBS = [
    ("No Animal Orb", 0),
    ("Cardinal", 1),
    ("Owlet", 2),
    ("Rammy", 3),
    ("Frogglet", 4),
    ("Monkeyface", 5),
    ("BiPolar Bear", 6),
    ("Bitey Bat", 7),
    ("Yeti", 8),
    ("Troll", 9),
    ("Snailburt", 10),
    ("Giraffey", 11),
    ("Zebra", 12),
    ("Meowburt", 13),
    ("Pazzo", 14),
    ("Burly Bear", 15),
    ("Hawkster", 16),
    ("Snoot", 17),
    ("Piggy", 18),
    ("Spiny", 19),
    ("Scratchpaw", 20),
    ("Seahorse", 21),
    ("Chicken", 22),
    ("Install Ball", 23),
    ("Mr. Buddy", 24),
    ("Sherbert", 25),
    ("Pelter", 26),
    ("Dragonhead", 27),
    ("Beholder", 28),
    ("Golden Whale", 29),
    ("Abilityless Golden Whale", 30),
]

RELIC_UNLOCKS = [
    ("No Relics", 0x00),
    ("Compass", 0x01),
    ("Wheel", 0x02),
    ("Compass + Wheel", 0x03),
    ("Telescope", 0x04),
    ("Compass + Telescope", 0x05),
    ("Wheel + Telescope", 0x06),
    ("Compass + Wheel + Telescope", 0x07),
    ("Horn", 0x08),
    ("Compass + Horn", 0x09),
    ("Wheel + Horn", 0x0A),
    ("Compass + Wheel + Horn", 0x0B),
    ("Telescope + Horn", 0x0C),
    ("Compass + Telescope + Horn", 0x0D),
    ("Wheel + Telescope + Horn", 0x0E),
    ("Compass + Wheel + Telescope + Horn", 0x0F),
    ("Compass (IM)", 0x1F),
    ("Wheel (IM)", 0x2F),
    ("Compass + Wheel (IM)", 0x3F),
    ("Telescope (IM)", 0x4F),
    ("Compass + Telescope (IM)", 0x5F),
    ("Wheel + Telescope (IM)", 0x6F),
    ("Compass + Wheel + Telescope (IM)", 0x7F),
    ("Horn (IM)", 0x8F),
    ("Compass + Horn (IM)", 0x9F),
    ("Wheel + Horn (IM)", 0xAF),
    ("Compass + Wheel + Horn (IM)", 0xBF),
    ("Telescope + Horn (IM)", 0xCF),
    ("Compass + Telescope + Horn (IM)", 0xDF),
    ("Wheel + Telescope + Horn (IM)", 0xEF),
    ("Compass + Wheel + Telescope + Horn (IM)", 0xFF),
]

SKULL_OPTIONS = [
    ("No Skull", 0x00),
    ("White Skull", 0x01),
    ("Gold Skull", 0x02),
]

# ========================
# Level Unlock Data
# ========================
# Each dict corresponds to one byte in memory.
# The values are cumulative bitmasks, where settings more bits means
# additional levels are unlocked in that progression chain.

NORMAL_LEVEL_UNLOCKS = [
    {
        "Unlocks Home Castle": 0x00,
        "Unlocks Blacksmith and Barbarian War": 0x01,
        "Unlocks Forest Entrance and Dock": 0x03,
        "Unlocks Abandoned Mill": 0x07,
        "Unlocks Tall Grass Field": 0x0F,
        "Unlocks Industrial Castle and Flowery Field": 0x1F,
        "Unlocks Cyclops' Cave": 0x3F,
        "Unlocks Lava World": 0x7F,
        "Lava World Completed": 0xFF,
    },
    {
        "Industrial Castle Completed": 0x01,
        "Unlocks Desert": 0x03,
        "Unlocks Sand Castle Interior": 0x07,
        "Unlocks Flooded Temple (Map Obtained)": 0x0F,
        "Marsh and Corn Boss Completed": 0x1F,
        "Unlocks Full Moon": 0x3F,
        "Unlocks Snow World": 0x7F,
        "Unlocks Wizard Castle Takeoff": 0xFF,
    },
    {
        "Wizard Castle and Final Battle Completed": 0x01,
    },
]

INSANE_LEVEL_UNLOCKS = [
    {
        "Unlocks Home Castle": 0x00,
        "Unlocks Blacksmith and Barbarian War": 0x01,
        "Unlocks Forest Entrance and Dock": 0x03,
        "Unlocks Abandoned Mill": 0x07,
        "Unlocks Tall Grass Field": 0x0F,
        "Unlocks Industrial Castle and Flowery Field": 0x1F,
        "Unlocks Cyclops' Cave": 0x3F,
        "Unlocks Lava World": 0x7F,
        "Lava World Completed": 0xFF,
    },
    {
        "Industrial Castle Completed": 0x01,
        "Unlocks Desert": 0x03,
        "Unlocks Sand Castle Interior": 0x07,
        "Unlocks Flooded Temple (Map Obtained)": 0x0F,
        "Marsh and Corn Boss Completed": 0x1F,
        "Unlocks Full Moon": 0x3F,
        "Unlocks Snow World": 0x7F,
        "Unlocks Wizard Castle Takeoff": 0xFF,
    },
    {
        "Wizard Castle and Final Battle Completed": 0x01,
    },
]


def flatten_level_unlocks(level_unlocks):
    """
    Converts structured unlock data into a flat list of (label, (array_index, value)) tuples.
    """
    flattened = []
    for array_index, mapping in enumerate(level_unlocks):
        for label, value in mapping.items():
            flattened.append((label, (array_index, value)))
    return flattened


# Flattened lists for easier access in UI or memory operations
NORMAL_LEVEL_UNLOCKS_FLAT = flatten_level_unlocks(NORMAL_LEVEL_UNLOCKS)
INSANE_LEVEL_UNLOCKS_FLAT = flatten_level_unlocks(INSANE_LEVEL_UNLOCKS)

# ========================
# UI / Display Metadata
# ========================

# Human-readable labels for stats display
STATS_DISPLAY = {
    "level": "Level",
    "exp": "Experience",
    "strength": "Strength",
    "defense": "Defense",
    "magic": "Magic",
    "agility": "Agility",
    "healthpots": "Health Potions",
    "bombs": "Bombs",
    "beefies": "Sandwiches",
    "gold": "Gold",
}

# ========================
# Memory Offsets
# ========================

# Field offsets inside the character struct (relative to struct start)
# Each entry specifies the memory offset and data type.
OFFSETS = {
    "is_character_unlocked": {"offset": 0, "type": "bool"},
    "level": {"offset": 1, "type": "byte"},
    "exp": {"offset": 2, "type": "int32"},
    "weapon": {"offset": 6, "type": "byte"},
    "animal_type": {"offset": 7, "type": "byte"},
    "strength": {"offset": 8, "type": "byte"},
    "defense": {"offset": 9, "type": "byte"},
    "magic": {"offset": 10, "type": "byte"},
    "agility": {"offset": 11, "type": "byte"},
    "normal_level_unlocks_0": {"offset": 12, "type": "byte"},
    "normal_level_unlocks_1": {"offset": 13, "type": "byte"},
    "normal_level_unlocks_2": {"offset": 14, "type": "byte"},
    "healthpots": {"offset": 15, "type": "byte"},
    "bombs": {"offset": 16, "type": "byte"},
    "beefies": {"offset": 17, "type": "byte"},
    "relic_unlocks": {"offset": 18, "type": "byte"},
    "gold": {"offset": 19, "type": "int32"},
    "insane_mode": {"offset": 23, "type": "byte"},
    "insane_level_unlocks_0": {"offset": 24, "type": "byte"},
    "insane_level_unlocks_1": {"offset": 25, "type": "byte"},
    "insane_level_unlocks_2": {"offset": 26, "type": "byte"},
    "skull": {"offset": 27, "type": "byte"},
}